# Generated by Django 2.2.5 on 2019-11-08 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='present_count',
            field=models.IntegerField(default=0),
        ),
    ]
