# Generated by Django 2.2.5 on 2019-11-08 18:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0002_auto_20191108_1811'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='class_enrolled',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='record.AttendanceRecord'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='attendancerecord',
            name='class_id',
            field=models.CharField(default='None', max_length=7),
        ),
        migrations.AlterField(
            model_name='attendancerecord',
            name='class_name',
            field=models.CharField(default='None', max_length=40),
        ),
    ]
