# Generated by Django 3.0 on 2019-12-07 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(default='None', max_length=40)),
                ('class_id', models.CharField(default='None', max_length=7)),
            ],
        ),
    ]
